#设置服务端口以及访问路径
server:
  port: 8080
  servlet:
    context-path: /group-system-service

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/payment
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
#设置日志存放地址以及日志级别
logging:
  path: ./applogs/
  pattern:
    level: info

