package com.springboot.mybaits.demo.dataobject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_id
     *
     * @mbg.generated Fri Jan 18 18:40:11 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_name
     *
     * @mbg.generated Fri Jan 18 18:40:11 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_password
     *
     * @mbg.generated Fri Jan 18 18:40:11 CST 2019
     */
    private String userPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_id
     *
     * @return the value of userinfo.user_id
     *
     * @mbg.generated Fri Jan 18 18:40:11 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_id
     *
     * @param userId the value for userinfo.user_id
     *
     * @mbg.generated Fri Jan 18 18:40:11 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_name
     *
     * @return the value of userinfo.user_name
     *
     * @mbg.generated Fri Jan 18 18:40:11 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_name
     *
     * @param userName the value for userinfo.user_name
     *
     * @mbg.generated Fri Jan 18 18:40:11 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_password
     *
     * @return the value of userinfo.user_password
     *
     * @mbg.generated Fri Jan 18 18:40:11 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_password
     *
     * @param userPassword the value for userinfo.user_password
     *
     * @mbg.generated Fri Jan 18 18:40:11 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }
}